#!/bin/bash
# This script install dependancies and configure the network for the raspberry pi server
# usage : bash setup.sh

thisScriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

if [[ $EUID -ne 0 ]]; then
   echo "Are you root enough ?" 
   exit 1
fi

echo "
------------installing dependencies :------------
"
echo "
updating the system :"
apt-get update||exit 1
apt-get -y dist-upgrade||exit 1
echo "
installing .deb packages :"
apt-get -y --fix-missing install python3-pip python3-dev liblo-dev libasound2-dev ||exit 1
echo "
installing pip packages :"
pip3 install Cython||exit 2
pip3 install pyliblo ||exit 2

echo "
------------DONE installing dependencies------------
"